#execute with : ansible-playbook site.yml -c local --extra-vars "mysql_root_password=qwe123 db_user=drupal7 db_password=qwe123 db_name=drupal7 drupal_uri=anydomain.com"
#default admin/admin123 password for panel
- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  
  roles:
   - common
